### ISSUE TITLE
Bluescreen on 64 bit systems

### ISSUE THREAD

**Issue by Beercow** [jeffbryner/NBDServer#8]
Please see this thread:
http://lists.volatilesystems.com/pipermail/vol-users/2013-April/000884.html

"The winpmem device driver allows you to read where ever you want (i.e. it does not protect you from shooting yourself in the foot :-). The user space application is supposed to figure out where its safe to read. From quickly looking at the code for nbdserve it does not seem to implement the correct algorithm for skipping the reserved memory regions (it should make an IO control to the pmem driver and ask it). There seems to be some code there to do it but it does not seem complete to me."

**Comment by Beercow** [comment]
Think I have this fixed. Planning on a pull request after some more testing. Leaving open for now.

**Comment by jeffbryner** [comment]
Cool, thanks much for the report. Report + fix == even better!

**Comment by Beercow** [comment]
Fixed in pull request #10
